# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-13 13:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190413_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 13, 25, 13, 447698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 13, 25, 13, 407698, tzinfo=utc)),
        ),
    ]
