# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-13 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190413_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(),
        ),
    ]
