# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-13 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190413_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 15, 50, 53, 509444, tzinfo=utc)),
        ),
    ]
