# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-17 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20190413_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 3, 28, 2, 77181, tzinfo=utc)),
        ),
    ]
