# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-03 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20190417_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nofication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 32, 26, 98865, tzinfo=utc)),
        ),
    ]
