# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-03 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20190503_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nofication',
            new_name='Notification',
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 33, 29, 36963, tzinfo=utc)),
        ),
    ]
