# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-03 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20190503_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 15, 35, 30, 78820, tzinfo=utc)),
        ),
    ]
