# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-28 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20190503_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrequest',
            name='bankname',
            field=models.CharField(default='Nil', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 15, 0, 57, 792385, tzinfo=utc)),
        ),
    ]
