# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-13 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20190528_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 4, 17, 44, 978421, tzinfo=utc)),
        ),
    ]
