# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-28 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20190613_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookingCode',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 5, 40, 36, 193850, tzinfo=utc)),
        ),
    ]
