# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-29 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20190628_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookingCode',
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 11, 37, 52, 867842, tzinfo=utc)),
        ),
    ]
