# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-09 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0015_auto_20190709_1930'),
        ('index', '0020_auto_20190709_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jimcontrol.Agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 18, 30, 23, 552027, tzinfo=utc)),
        ),
    ]
