# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-09 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20190709_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 21, 8, 27, 168718, tzinfo=utc)),
        ),
    ]
