# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-12 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0002_auto_20190412_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(default='jimnet@gmail.com', max_length=500),
        ),
    ]
