# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-13 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0003_adminuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='lastlogin',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 13, 15, 41, 705429, tzinfo=utc)),
        ),
    ]
