# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-13 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0004_staff_lastlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='lastlogin',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 13, 17, 23, 970150, tzinfo=utc)),
        ),
    ]
