# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-13 13:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0005_auto_20190413_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='lastlogin',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 13, 25, 13, 387698, tzinfo=utc)),
        ),
    ]
