# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-13 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0007_auto_20190413_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='lastlogin',
            field=models.DateTimeField(),
        ),
    ]
