# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-13 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0008_auto_20190413_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 6, 13, 4, 17, 44, 962821, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='adminuser',
            name='note',
            field=models.IntegerField(default=0),
        ),
    ]
