# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-28 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0010_auto_20190628_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 5, 16, 12, 749157, tzinfo=utc)),
        ),
    ]
