# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-29 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0012_auto_20190628_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 11, 37, 52, 852242, tzinfo=utc)),
        ),
    ]
