# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-09 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0013_auto_20190629_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=1000)),
                ('lastlogin', models.DateTimeField()),
                ('phoneno', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 15, 44, 41, 648023, tzinfo=utc)),
        ),
    ]
