# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-09 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0014_auto_20190709_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 18, 30, 23, 532027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='agent',
            name='lastlogin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
