# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-21 11:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0016_auto_20190709_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 11, 56, 9, 97687, tzinfo=utc)),
        ),
    ]
